export const RESET_GARDEN = 'RESET_GARDEN';
export const LOAD_GARDEN = 'LOAD_GARDEN';
export const UPDATE_GARDEN_SQUARE = 'UPDATE_GARDEN_SQUARE';
export const RESET_GARDEN_SQUARE = 'RESET_GARDEN_SQUARE';

export const SET_GARDEN_DRAWER_CONTEXT = 'SET_GARDEN_DRAWER_CONTEXT';
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const SELECT_PLANT = 'SELECT_PLANT';
